apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-deploy
  labels:
    app: javaapp
spec:
  replicas: 0
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        image: sreejitheyne/openjdk:17.0.2
        ports:
        - containerPort: 8040




---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: javaapp
  ports:
  - protocol: TCP
    port: 8040
    targetPort: 8040
  type: NodePort
